const LANG_PACK = {
    ar: {
        // Titles & Nav
        home_title: "أهلاً بك في BTC-CloudX",
        home_subtitle: "بوابتك الآمنة للاستثمار في مستقبل التعدين السحابي. ابدأ رحلتك الاستثمارية معنا اليوم.",
        plans_title: "📊 الخطط الاستثمارية المميزة",
        hardware_title: "📠 أجهزتنا للتعدين",
        custom_plan_title: "💡 صمّم خطتك الاستثمارية",
        faq_title: "❓ أسئلة شائعة",
        nav_home: "الرئيسية",
        nav_plans: "الخطط",
        nav_hardware: "الأجهزة",
        nav_custom_plan: "خطة خاصة",
        nav_faq: "الأسئلة",
        back_text: "العودة",
        // Platform Elements
        platform_tagline: "منصة التعدين السحابي الرائدة",
        article_title: "تحسين واجهة المستخدم",
        article_content: "منصة التعدين السحابية في حاجة للمعالجة الآن حرصاً على أموالكم. نحن نعمل على تحسين الأمان والأداء لضمان أفضل تجربة استثمارية لعملائنا الكرام.",
        article_note: "💡 سيتم إشعاركم بانتهاء أعمال الصيانة قريباً",
        enter_platform_text: "تحسين واجهة المستخدم",
        maintenance_subtitle: "منصة التعدين السحابية في حاجة للمعالجة الآن",
        // Coupon System
        coupon_title: "كوبون المكافآت الشهرية",
        reveal_coupon_text: "اكشف كوبونك الآن",
        coupon_code_label: "كود الاشتراك الخاص بك:",
        rewards_title: "مكافأتك:",
        reward_amount: "مكافأة 15$ أسبوعياً",
        reward_condition: "متاح سحبها مع استلام أرباح الشهر الثالث",
        countdown_label: "انتهاء الكوبون خلال:",
        days_label: "يوم",
        hours_label: "ساعة",
        minutes_label: "دقيقة",
        // Plans
        investment: "الاستثمار",
        hashrate: "القوة التعدينية",
        device: "الجهاز المصدر",
        daily_profit: "الربح اليومي الصافي",
        annual_profit: "الربح السنوي الصافي",
        semi_annual_bonus: "عائد نصف سنوي",
        subscribe_now: "اشترك الآن",
        // Hardware
        efficiency: "الكفاءة",
        hardware_modal_info: "هذا الجهاز من أفضل الأجهزة في فئته، ويستخدم في خططنا لضمان أعلى عائد ممكن للمستثمرين.",
        // Custom Plan
        custom_plan_amount_label: "1. حدد مبلغ الاستثمار (بالدولار)",
        custom_plan_amount_placeholder: "الحد الأدنى 1000 دولار",
        custom_plan_duration_label: "2. حدد مدة العقد (سنوات)",
        year_one: "سنة واحدة",
        year_two: "سنتان",
        year_three: "3 سنوات",
        year_unit: "سنة",
        calculate_button: "احسب الخطة",
        custom_plan_results_title: "نتائج خطتك المخصصة",
        estimated_hashrate: "القوة التعدينية المقدرة",
        estimated_daily_profit: "صافي الربح اليومي المقدر",
        total_mining_profit: "إجمالي ربح التعدين",
        additional_bonus: "العائد الإضافي (25% كل 6 شهور)",
        total_estimated: "الإجمالي الكلي المتوقع",
        disclaimer: "هذه الأرقام تقديرية وتعتمد على سعر البيتكوين الحالي وصعوبة الشبكة.",
        submit_plan_button: "أرسل الخطة للبوت واطلبها",
        // Modals
        confirm_subscription: "تأكيد الاشتراك",
        confirm_subscription_q: "هل تريد تأكيد الاشتراك في الخطة التالية؟",
        plan: "الخطة",
        price: "السعر",
        power: "القوة",
        yes_confirm: "نعم، أوافق",
        no_cancel: "لا، تراجع",
        // FAQ
        FAQ_DATA: [
            { q: 'ما طبيعة عملكم؟', a: 'نحن شركة BTC-CloudX، نوفر لك فرصة للاستثمار في تعدين العملات الرقمية عبر شراء قوة تعدينية (Hashrate) من مزارعنا المجهزة بأحدث الأجهزة. نتولى كل شيء، من الصيانة والتشغيل، وأنت تحصل على الأرباح بشكل يومي.' },
            { q: 'كيف تُحسب الأرباح؟', a: 'تعتمد الأرباح على القوة التعدينية التي تملكها، وسعر البيتكوين الحالي، وصعوبة الشبكة. تُخصم رسوم الكهرباء والصيانة يوميًا من الناتج الإجمالي، والمتبقي هو ربحك الصافي. الاستثمار ينطوي على مخاطر تقلب الأسعار.' },
            { q: 'هل أحصل على شهادة أو إثبات؟', a: 'نعم، عند الاشتراك في أي خطة، ستحصل على شهادة استثمار رقمية تحتوي على تفاصيل عقدك، بالإضافة إلى مُعرّف اشتراك فريد (ID) خاص بك لمتابعة استثمارك.' },
            { q: 'كيف يمكنني التواصل مع الدعم الفني؟', a: 'يمكنك التواصل مع فريق الدعم مباشرة عبر زر "تواصل معنا" في البوت، أو الانضمام إلى قناتنا على تليجرام لمتابعة آخر الأخبار وتحديثات الأرباح.' }
        ]
    },
    en: {
        home_title: "Welcome to BTC-CloudX",
        home_subtitle: "Your secure gateway to invest in the future of cloud mining. Start your investment journey with us today.",
        plans_title: "📊 Featured Investment Plans",
        hardware_title: "📠 Our Mining Hardware",
        custom_plan_title: "💡 Design Your Investment Plan",
        faq_title: "❓ Frequently Asked Questions",
        nav_home: "Home",
        nav_plans: "Plans",
        nav_hardware: "Hardware",
        nav_custom_plan: "Custom Plan",
        nav_faq: "FAQ",
        back_text: "Back",
        // Platform Elements
        platform_tagline: "Leading Cloud Mining Platform",
        article_title: "User Interface Improvement",
        article_content: "The cloud mining platform needs processing now to safeguard your funds. We are working on improving security and performance to ensure the best investment experience for our valued clients.",
        article_note: "💡 You will be notified when maintenance work is completed soon",
        enter_platform_text: "User Interface Improvement",
        maintenance_subtitle: "Cloud mining platform needs maintenance now",
        // Coupon System
        coupon_title: "Monthly Rewards Coupon",
        reveal_coupon_text: "Reveal Your Coupon Now",
        coupon_code_label: "Your subscription code:",
        rewards_title: "Your Reward:",
        reward_amount: "$15 Weekly Reward",
        reward_condition: "Available for withdrawal with third month profits",
        countdown_label: "Coupon expires in:",
        days_label: "Day",
        hours_label: "Hour",
        minutes_label: "Minute",
        // Plans
        investment: "Investment",
        hashrate: "Hashrate",
        device: "Source Device",
        daily_profit: "Net Daily Profit",
        annual_profit: "Net Annual Profit",
        semi_annual_bonus: "Semi-Annual Bonus",
        subscribe_now: "Subscribe Now",
        efficiency: "Efficiency",
        hardware_modal_info: "This device is one of the best in its class, used in our plans to ensure the highest possible return for investors.",
        custom_plan_amount_label: "1. Set Investment Amount (USD)",
        custom_plan_amount_placeholder: "Minimum $1000",
        custom_plan_duration_label: "2. Set Contract Duration (Years)",
        year_one: "1 Year",
        year_two: "2 Years",
        year_three: "3 Years",
        year_unit: "Year",
        calculate_button: "Calculate Plan",
        custom_plan_results_title: "Your Custom Plan Results",
        estimated_hashrate: "Estimated Hashrate",
        estimated_daily_profit: "Estimated Net Daily Profit",
        total_mining_profit: "Total Mining Profit",
        additional_bonus: "Additional Bonus (25% every 6 months)",
        total_estimated: "Total Estimated Return",
        disclaimer: "These figures are estimates and depend on the current Bitcoin price and network difficulty.",
        submit_plan_button: "Send Plan to Bot and Request It",
        confirm_subscription: "Confirm Subscription",
        confirm_subscription_q: "Do you want to confirm your subscription to the following plan?",
        plan: "Plan",
        price: "Price",
        power: "Power",
        yes_confirm: "Yes, I Agree",
        no_cancel: "No, Go Back",
        FAQ_DATA: [
            { q: 'What is the nature of your work?', a: 'We are BTC-CloudX. We provide you with an opportunity to invest in cryptocurrency mining by purchasing hashrate from our farms equipped with the latest hardware. We handle everything, from maintenance to operation, and you receive the profits daily.' },
            { q: 'How are profits calculated?', a: 'Profits depend on the hashrate you own, the current Bitcoin price, and network difficulty. Electricity and maintenance fees are deducted daily from the gross output, and the remainder is your net profit. Investment involves risks of price volatility.' },
            { q: 'Do I get a certificate or proof?', a: 'Yes, when you subscribe to any plan, you will receive a digital investment certificate with your contract details, in addition to a unique subscription ID to track your investment.' },
            { q: 'How can I contact technical support?', a: 'You can contact the support team directly via the "Contact Us" button in the bot, or join our Telegram channel to follow the latest news and profit updates.' }
        ]
    },
    zh: {
        home_title: "欢迎来到 BTC-CloudX",
        home_subtitle: "您投资云挖矿未来的安全门户。立即与我们一起开始您的投资之旅。",
        plans_title: "📊 特色投资计划",
        hardware_title: "📠 我们的矿机硬件",
        custom_plan_title: "💡 设计您的投资计划",
        faq_title: "❓ 常见问题",
        nav_home: "首页",
        nav_plans: "计划",
        nav_hardware: "硬件",
        nav_custom_plan: "定制计划",
        nav_faq: "常见问题",
        back_text: "返回",
        // Platform Elements
        platform_tagline: "领先的云挖矿平台",
        article_title: "用户界面改进",
        article_content: "云挖矿平台现在需要处理以保护您的资金。我们正在努力改进安全性和性能，以确保为我们尊贵的客户提供最佳的投资体验。",
        article_note: "💡 维护工作完成后将很快通知您",
        enter_platform_text: "用户界面改进",
        maintenance_subtitle: "云挖矿平台现在需要维护",
        // Coupon System
        coupon_title: "月度奖励优惠券",
        reveal_coupon_text: "立即显示您的优惠券",
        coupon_code_label: "您的订阅代码：",
        rewards_title: "您的奖励：",
        reward_amount: "每周15美元奖励",
        reward_condition: "可在第三个月利润中提取",
        countdown_label: "优惠券到期时间：",
        days_label: "天",
        hours_label: "小时",
        minutes_label: "分钟",
        // Plans
        investment: "投资",
        hashrate: "算力",
        device: "源设备",
        daily_profit: "每日净利润",
        annual_profit: "年度净利润",
        semi_annual_bonus: "半年奖金",
        subscribe_now: "立即订阅",
        efficiency: "效率",
        hardware_modal_info: "该设备是同类产品中最好的设备之一，用于我们的计划，以确保为投资者带来尽可能高的回报。",
        custom_plan_amount_label: "1. 设置投资金额（美元）",
        custom_plan_amount_placeholder: "最低1000美元",
        custom_plan_duration_label: "2. 设置合同期限（年）",
        year_one: "1年",
        year_two: "2年",
        year_three: "3年",
        year_unit: "年",
        calculate_button: "计算计划",
        custom_plan_results_title: "您的自定义计划结果",
        estimated_hashrate: "预计算力",
        estimated_daily_profit: "预计每日净利润",
        total_mining_profit: "总挖矿利润",
        additional_bonus: "额外奖金（每6个月25%）",
        total_estimated: "预计总回报",
        disclaimer: "这些数字是估算值，取决于当前的比特币价格和网络难度。",
        submit_plan_button: "将计划发送给机器人并请求",
        confirm_subscription: "确认订阅",
        confirm_subscription_q: "您要确认订阅以下计划吗？",
        plan: "计划",
        price: "价格",
        power: "算力",
        yes_confirm: "是的，我同意",
        no_cancel: "不，返回",
        FAQ_DATA: [
            { q: '你们的工作性质是什么？', a: '我们是 BTC-CloudX。我们为您提供投资加密货币挖矿的机会，您可以从我们配备最新硬件的矿场购买算力。我们处理从维护到运营的一切事务，您每天都能获得利润。' },
            { q: '利润是如何计算的？', a: '利润取决于您拥有的算力、当前的比特币价格和网络难度。电费和维护费每天从总产出中扣除，余下的是您的净利润。投资涉及价格波动的风险。' },
            { q: '我能获得证书或证明吗？', a: '是的，当您订阅任何计划时，您将收到一份包含合同详情的数字投资证书，以及一个用于跟踪您投资的唯一订阅ID。' },
            { q: '我如何联系技术支持？', a: '您可以直接通过机器人中的"联系我们"按钮联系支持团队，或加入我们的Telegram频道以获取最新消息和利润更新。' }
        ]
    }
};
